name: Format

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-format:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure clang-format
        run: |
          brew update
          brew list clang-format >/dev/null 2>&1 || brew install clang-format

      - name: Run formatting check
        run: |
          chmod +x ./scripts/format.sh
          ./scripts/format.sh --check
