name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Ensure build tools
        run: |
          brew update
          brew list cmake || brew install cmake

       - name: Run unit tests
         run: |
           chmod +x ./scripts/test.sh || true
           ./scripts/test.sh
