name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Ensure build tools
        run: |
          brew update
          brew list cmake || brew install cmake

      - name: Run unit tests
        run: |
          chmod +x ./test.sh || true
          ./test.sh
